GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibWFyaWEiLCJpYXQiOjE3NDI5OTY4OTQsImV4cCI6MTc0Mjk5NjkxNH0.PohIktV-4prSMepPDdNnDp47mrdHOlKC0gzsSBx3qrU



###

DELETE http:localhost:4000/logout
Content-Type:  application/json

{
  "token": ""
}


###


POST http://localhost:4000/token
Content-Type: application/json

{
  "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibWFyaWEiLCJpYXQiOjE3NDI5OTY4OTR9.1ZTyxSqWxM-Dh7pDsDQDz2jJiPMbLqUm_wJC-WX8KC4"
}


###

POST http://localhost:4000/login
Content-Type: application/json

{
  "username":"maria"
}


 